### ISSUE TITLE
Cached images and preload 

### ISSUE THREAD

**Issue by jslok** [DylanVann/react-native-fast-image#68] opened 2017-09-30 06:59 UTC
1. When user views screen with image1, image1 downloads and fades into view.
2. Navigate away, then again to screen with image1. Image1 is in view already and doesn't need the fade-in animation.
3. Restart app
4. When user views screen with image1, image1 fades into view.

If the image is cached already from step 1/2, shouldn't the image not need to download and fade-in again in step 4? Why does it do the fade-in animation again after restarting the app?

Is preload meant to have any effect on the fade-in? When I tried preloading images there was no effect.

My goal is to just remove the fade-in since the image was already downloaded previously and the image should just already be on screen. Is this possible?

**Comment by wkoutre** [comment] 2017-10-26 17:18
@jslok Have you figured anything out related to this?

**Comment by jslok** [comment] 2017-10-27 01:20
@wkoutre Unfortunately I have not. Will probably need help to figure it out as I don't know too much about how the cache/preload works.

**Comment by wkoutre** [comment] 2017-10-27 22:38
@jslok Neither do I, to be honest.

When I have time this weekend/next week, I'll be looking into it. Preload seems to work better on simulators than actual devices.

In my app, when a user logs in, I fetch data which include many URI to images (profile pics, favorite pics, etc). I create an array of objects, each with a `uri` property, then call `FastImage.preload` with the array as the param.

It doesn't seem to work 100% of the time, though. I'll post back here as I look into it more.

**Comment by DylanVann** [comment] 2018-02-01 01:52
Preload was 100% not working on Android, it has been fixed in the new version. Thank you for the help!

**Closed by DylanVann** 2018-02-01 01:52 UTC

**Comment by cyclops24** [comment] 2018-02-07 15:44
@DylanVann Any news about Image Preload feature on Android?

**Comment by Donhv** [comment] 2019-11-14 11:05
@DylanVann have any update in android?

**Comment by 94dado** [comment] 2020-12-06 16:26
@DylanVann the problem is still present. Any update?

**Comment by NemyaNation** [comment] 2022-05-29 10:14
@DylanVann @94dado @Donhv @jslok @cyclops24 @wkoutre 

Anyone figure this out?
