### ISSUE TITLE
Curious your thoughts on memory usage vs RN's <Image />

### ISSUE THREAD

**Issue by JAStanton** [DylanVann/react-native-fast-image#70] opened 2017-10-05 22:15 UTC
Hey so my app loads a lot of images remotely, and allows users to take photos and upload them. I see a fair number of memory related issues in my app as a result. Particularly my API doesn't thumbnail any images so remote images load in as large images and from what I can tell from RN's `<Image />` is that it's not giving me a ton of support in downsampling. Thus lots of crashes.

I'm curious your evaluation on what RN's `<Image />` is doing on iOS and Android to help with local and remote image in regards to memory / disk consumption. And how this differs from react-native-fast-image (and the underlying Glide / SDWebImage)

Any insight would be very helpful, thank you!

**Comment by pavanmehta91** [comment] 2017-11-10 06:19
I'm also having multiple (100+) images to load and show and I've not downsized them yet. I tried FastImage component and my app crashed. Maybe it was due to memory, it was trying to cache 100+ images at one go. While using <Image /> Component my app rarely crashes but images load each time the user opens the app again.

**Comment by yomybaby** [comment] 2017-11-23 06:12
Me too. Many `FastImage` on Flatlist are crashes on iPhone 5. (iPhone SE work properly)
After changing to `Image`, iPhone 5 works properly too. 
I love aggressive cashing but I can't use this because crashing. 😢

**Comment by kevinresol** [comment] 2017-12-05 09:53
I can confirm the memory issue. I have a FlatList with ~200 `FastImage`, at any time there will be 9 - 12 images visible (a 3 column by 3 row layout). When using FastImage the memory usage (as seen in xcode) shoots up to 600MB and the app crashes. This happens when I scroll the list down to around the 100th image.

As a reference value, when using RN Image, the memory usage is ~20MB.

**Comment by bitshadow** [comment] 2018-01-27 04:10
<img width="717" alt="screen shot 2018-01-27 at 9 37 48 am" src="https://user-images.githubusercontent.com/574802/35468530-d82e1426-0345-11e8-8bfc-3969943c3cf2.png">

My memory profiler shows that react-native-fast-image uses 383.83 MB for loading only (5 images worth 1KB each).

**Comment by pavanmehta91** [comment] 2018-01-30 05:41
@bitshadow  which app is that you're using for profiling?

**Comment by bitshadow** [comment] 2018-02-10 10:12
@pavanmehta91 I have just written https://medium.com/@bitshadow/finding-memory-leaks-react-native-app-ios-46e6eeb50c8c . Hope this is helpful.

**Comment by jslok** [comment] 2018-02-13 04:41
Thanks for writing that article @bitshadow. Did you do any testing on android or is it not an issue on there?

I'm seeing the same issue and crashes on my app for ios. react-native-fast-image never releases the memory. This seems to be fixed by setting _shouldCacheImagesInMemory = NO in \node_modules\react-native-fast-image\ios\Vendor\SDWebImage\SDWebImage but it looks like fast-image still uses 1.5-2x more memory than rn Image component.

**Comment by jacksontbryan** [comment] 2018-02-14 17:32
I am seeing memory use shoot up leading to crashes while new images are loading (and being cached).  If they are already cached everything loads fine.

**Comment by DylanVann** [comment] 2018-04-27 03:10
It may just be that you need to figure out a way to thumbnail the images. If you want to show the images quickly there's no way to download only part of them so memory usage is necessarily going to spike.

We should be able to slow it down and prevent a crash though. I'm going to close this in favour of this issue: https://github.com/DylanVann/react-native-fast-image/issues/195

**Closed by DylanVann** 2018-04-27 03:10 UTC
Labels: question
