### ISSUE TITLE
FastImage :Breaks in android 

### ISSUE THREAD

**Issue by GeekRishabh** [DylanVann/react-native-fast-image#10] opened 2017-06-13 14:37 UTC
when i am using some thing like 
```
<FastImage
            source={{
              uri: item.blurredImageUrl,
            }}
            resizeMode={FastImage.resizeMode.cover}
            style={Style.modalHeaderBgImage}
          >
            <View>
              <FastImage
                source={{
                  uri: iconUrl,
                  priority: FastImage.priority.high,
                }}
                style={Style.modalHeaderImage}
                resizeMode={FastImage.resizeMode.stretch}
              />
            </View>
            <View style={Style.modalHeaderRight}>
              
              <Text>
                ENDS IN 
              </Text>
            </View>
          </FastImage>

```

when i use this libary on Android, it show an error:
"android.widget.imageview cannot be cast to android.view.viewgroup".

Please resolve this issue . Works fine in IOS . Need it urgently

**Comment by aschenkel** [comment] 2017-06-15 06:09
I don't think FastImage component should have children. Or should they? Have you try removing the children and write them as siblings components? Check [this](https://stackoverflow.com/questions/44425953/android-widget-imageview-cannot-be-cast-to-android-view-viewgroup-only-in-andro/44559648#44559648) out

**Comment by angelstoone** [comment] 2017-06-16 10:44
It seems that this is a duplicate of the issue #7

**Comment by aschenkel** [comment] 2017-06-16 15:37
Definitely duplicate. FastImage shouldn't have child components if you want to target android.

**Comment by DylanVann** [comment] 2017-06-20 07:17
Thanks for the issue. See #15 .

**Closed by DylanVann** 2017-06-20 07:17 UTC
