### ISSUE TITLE
BorderRadius Android

### ISSUE THREAD

**Issue by Amurmurmur** [DylanVann/react-native-fast-image#25] opened 2017-07-26 01:14 UTC
On iOS it works as expected, but on Android, borderRadius does not get applied, the image stays squared.

Here is the code I use:
```
<FastImage 
   source={{uri: 'https://example.com'} 
   style={styles.picture} 
   borderRadius={75} 
   resizeMode="cover"
/>
```
and styles.picture has the following:

```
    width: 150,
    height: 150,
    borderRadius: 75,
    borderWidth: 0.5,
    borderColor: 'grey',
    backgroundColor: 'transparent',
```

So I tried to double set it through props and through style object.

No luck :/
Running:
RN v0.46.2
Android 5.0.1
RNFI v0.0.11

**Comment by MrLoh** [comment] 2017-10-06 19:40
duplicate of #2

**Comment by dotansimha** [comment] 2017-10-12 20:12
Any progress on this issue?

**Comment by MrLoh** [comment] 2017-10-12 20:57
just use https://github.com/vovkasm/react-native-web-image for android. And someone should close this duplicate probably.

**Comment by dotansimha** [comment] 2017-10-12 21:19
@MrLoh Yeah that's was I did... Thanks

**Comment by DylanVann** [comment] 2017-11-06 03:56
I will look into adding support. Closing this in favour of https://github.com/DylanVann/react-native-fast-image/issues/2 .

**Closed by DylanVann** 2017-11-06 03:56 UTC

**Comment by MrLoh** [comment] 2017-11-06 08:19
That’s awesome. Thanks
