### ISSUE TITLE
Native android implementation does not accept Children

### ISSUE THREAD

**Issue by pavanmehta91** [DylanVann/react-native-fast-image#83] opened 2017-11-14 12:20 UTC
I've made a placeholder wrapper by changing a bit of code in FastImage.js by accepting {this.props.children} however it only works in ios and <FastImageView> does not accept any children for android.

````
class FastWrapper extends Component {
     state = {
       hidePlaceHolder: false
    }
    render() {
      let placeHolderStyle = Object.assign({},this.props.style,{zIndex:2});
      console.log('in render', this.props.source);
      return (
         <FastImage
           style={this.props.style}
           source={this.props.source}
            onLoadStart= {()=>{
             console.log('on load Start for image called', this.props.source);
           }}
           onLoad = {()=>{
             this.setState({hidePlaceHolder: true});
             console.log('on load for image called');  
          }}
         >
           { !this.state.hidePlaceHolder && !(Platform.OS === 'android') ?
          <Image
            style={placeHolderStyle}
            source={Images.placeHolder}
          /> 
          : null
         }
         </FastImage>
     )
    }
  }
````

Here's the code for my wrapper for FastImage. Right now i've disabled it for android. I want placeholders for android too.

**Comment by tonygentilcore** [comment] 2017-11-16 03:00
Duplicate of #15?

**Closed** 2017-11-16 07:32 UTC

**Comment by DylanVann** [comment] 2018-03-18 12:39
It accepts children now. It's using a wrapper for that so that the native code doesn't have to be changed.

**Comment by pavanmehta91** [comment] 2018-03-18 13:51
Thanks @DylanVann  :)
