### ISSUE TITLE
NullPointerException: Attempt to invoke virtual method ... in Nexus 5X (Android)

### ISSUE THREAD

**Issue by hamidfzm** [DylanVann/react-native-fast-image#588] opened 2019-10-20 23:44 UTC
**Describe the bug**
I'm getting the following error from my crash analytics in Nexus 5X devices that installed my app:
https://sentry.io/share/issue/f99e6147b26842ada4e04ddd83c59a0b/

**To Reproduce**
I used fast images like the example in a Nexus 5X device to display images from WebServer but every time app crashes.

**Expected behavior**
Display images properly.

**Dependency versions**

- React Native version: 0.61.2
- React version: 16.8.1
- React Native Fast Image version: 7.0.2
- Device: Nexus 5X
- OS: Android 6.0.1

**Comment by meosieudang** [comment] 2020-01-17 04:09
any one fix it?

**Comment by philipheinser** [comment] 2020-02-04 03:38
@hamidfzm Did you add these pro guard rules?

```
-keep public class com.dylanvann.fastimage.* {*;}
-keep public class com.dylanvann.fastimage.** {*;}
-keep public class * implements com.bumptech.glide.module.GlideModule
-keep public class * extends com.bumptech.glide.module.AppGlideModule
-keep public enum com.bumptech.glide.load.ImageHeaderParser$** {
  **[] $VALUES;
  public *;
}
```

**Comment by hamidfzm** [comment] 2020-02-08 20:07
@philipheinser Yes.

**Comment by DylanVann** [comment] 2020-03-12 22:49
Looks like this is a duplicate of https://github.com/DylanVann/react-native-fast-image/issues/536

**Closed by DylanVann** 2020-03-12 22:49 UTC
Labels: bug
