### ISSUE TITLE
Error:(20, 5) error: method does not override or implement a method from a supertype

### ISSUE THREAD

**Issue by AlmogRnD** [DylanVann/react-native-fast-image#48] opened 2017-08-21 16:32 UTC
Getting the following issues when trying to build for Android works for iOS

`/Users/Almog/Full-Time-Employment/Construction-Cloud/RnD/CCMobileApp/node_modules/react-native-fast-image/android/src/main/java/com/dylanvann/fastimage/FastImageViewPackage.java`
`Error:(20, 5) error: method does not override or implement a method from a supertype`

```
Error:Execution failed for task ':react-native-fast-image:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

Any ideas how to fix this?

**Comment by AlmogRnD** [comment] 2017-08-24 16:32
Any updates on this?

**Comment by arabscimitar** [comment] 2017-08-29 00:45
#47

**Comment by DylanVann** [comment] 2018-03-18 12:49
Duplicate of https://github.com/DylanVann/react-native-fast-image/issues/47

**Closed by DylanVann** 2018-03-18 12:49 UTC
