### ISSUE TITLE
borderRadius on android cause sawtooth.

### ISSUE THREAD

**Issue by yqz0203** [DylanVann/react-native-fast-image#153] opened 2018-02-27 02:24 UTC
On ios borderRadius works fine and the edge is smooth, but on android the edge has sawtooth.

**Comment by DylanVann** [comment] 2018-03-08 04:26
This is an issue with `react-native` core. I'm hoping to submit a PR to address it at some point.

This actually isn't apparent on high DPI phones.

**Comment by DylanVann** [comment] 2018-05-04 03:26
@Agoujil2saad Awesome. I'll keep an eye out for it in the next release notes then close this when I have a chance to test.

**Closed** 2018-06-10 03:06 UTC
Labels: React Native, bug

**Comment by matpaul** [comment] 2018-12-15 17:58
@DylanVann hi, on 5.1.1 and rn 0.57.5 we reproduce same sharp effect (sawtooth) 
```jsx
<View style={{width:20, height:20, borderRadius: 10}}>
   <FastImage source={...} style={{width:20, height:20}}> 
...
```

**Comment by RageOfJustice** [comment] 2019-03-13 10:52
@DylanVann Hi! It seems fixed on Image RN component (0.59.0). But still sawtooth with FastImage component

**Comment by Twinski** [comment] 2020-04-29 10:21
Is there any update on this? I can reproduce sharp edges on android on FastImage, when using borderRadius

**Comment by excitedcat** [comment] 2020-06-04 08:53
The problem still exists !

**Comment by pqminh** [comment] 2021-04-19 17:15
+1

**Comment by DylanVann** [comment] 2021-09-15 21:26
Cannot reproduce, please open another issue with an example showing. If it's only older versions of RN or Android it probably will not be fixed.
