### ISSUE TITLE
Encounter error when running command react-native run-ios

### ISSUE THREAD

**Issue by luanltt** [DylanVann/react-native-fast-image#102] opened 2017-12-11 10:07 UTC
Hi,

Does anyone encounter below error when running command `react-native run-ios`?

```
The following build commands failed:

	CompileC /Users/luan/work/ltt/projects/pet/repo/PetAppDev/ios/build/Build/Intermediates.noindex/SDWebImage.build/Release-iphoneos/SDWebImage\ iOS\ static.build/Objects-normal/armv7/FLAnimatedImageView+WebCache.o SDWebImage/FLAnimatedImage/FLAnimatedImageView+WebCache.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
```

But when I build and run app via Xcode I do not encounter any error.

Thank you!

**Comment by MrLoh** [comment] 2017-12-12 11:27
duplicate of #46

**Closed** 2018-03-18 12:50 UTC
