### ISSUE TITLE
blureRadius is not supported

### ISSUE THREAD

**Issue by nimamyscreen** [DylanVann/react-native-fast-image#62] opened 2017-09-14 04:56 UTC
blurerRaduis Image is supported in react-native 46 and your RN version is 45 , plz upgrade your RN version to at least 46.

**Comment by chrise86** [comment] 2017-09-20 09:32
Duplicate of https://github.com/DylanVann/react-native-fast-image/issues/50

**Comment by DylanVann** [comment] 2018-03-18 12:10
Upgrading the version of RN will not fix this as this does not use the RN Image component.

Dupe https://github.com/DylanVann/react-native-fast-image/issues/50

**Closed by DylanVann** 2018-03-18 12:10 UTC
